### ISSUE TITLE
Support BasicAuth and KeyAuth based authentication

### ISSUE THREAD

**Issue by saltbo** [envoyproxy/gateway#1660] opened 2023-07-14 10:20 UTC
*Description*:

Support BasicAuth and KeyAuth based authentication

[optional *Relevant Links*:]

https://github.com/envoyproxy/envoy/issues/15365

**Comment by zhaohuabing** [comment] 2023-07-18 02:06
EG can support BasicAuth after the [credential injector http filter ](https://github.com/envoyproxy/envoy/pull/27769) is finished.

**Comment by arkodg** [comment] 2023-09-21 00:14
thinking out loud
* the user could represent the username password in the format used by `htpasswd`
https://httpd.apache.org/docs/2.4/programs/htpasswd.html
* which can be stored in a k8s secret
* we could use SDS to pass this info over to Envoy
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/secret.proto#secrets-configuration-proto
* last step in Envoy involves allowing the request if the `Authorization` header matches with one of the user:passwd entries, @zhaohuabing @cpakulski any idea how we can achieve this one ?

and something similar could be done for API Key as well

**Comment by zhaohuabing** [comment] 2023-09-21 01:57
@arkodg AFAIK, Envoy doesn't have built-in BasicAuth or API key support. But it may be accomplished by extensions such as lua, wasm, or  External Authorization.

**Comment by zhaohuabing** [comment] 2023-10-31 03:40
Basic Auth has been merged into Envoy. https://github.com/envoyproxy/envoy/pull/30079. I plan to add it to the SecurityPolicy in the next release.

**Comment by arkodg** [comment] 2023-11-16 17:46
@zhaohuabing can we reuse the same Envoy Filter for API key auth ?

**Comment by zhaohuabing** [comment] 2023-11-16 18:03
> @zhaohuabing can we reuse the same Envoy Filter for API key auth ? 

The problem is, unlike HTTP Basic Auth, there's no standard for API key auth. We may improve the http basic auth filter or and another filter to support API key auth following open API specs: https://swagger.io/docs/specification/authentication/api-keys/#:~:text=API%20keys%20are%20supposed%20to,mechanisms%20such%20as%20HTTPS%2FSSL.

**Comment by arkodg** [comment] 2023-11-16 18:41
yeah nice, it would look a lot like `from_headers` in https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#extensions-filters-http-jwt-authn-v3-jwtprovider

**Comment by zhaohuabing** [comment] 2023-12-09 08:26
Key auth is not supported yet. We can open another issue to track it.

**Comment by zhaohuabing** [comment] 2023-12-09 08:27
Key auth is not supported yet. We can open another issue to track it.

**Closed** 2024-02-16 02:31 UTC
Labels: kind/enhancement, help wanted, area/policy
