### ISSUE TITLE
Support for TLS termination for TCP protocol?

### ISSUE THREAD

**Issue by gitanuj** [envoyproxy/gateway#686] opened 2022-11-03 05:28 UTC
*Description*:
Is it possible to support TLS termination for TCP protocol?

I'm trying to use envoy gateway as an API gateway which accepts TCP connection from a client and does SSL termination and then proxies the request down to a service in the cluster which also accepts TCP connection with SSL using a self signed cert. Is this something envoy gateway can support?

Currently TLS Termination is only supported for HTTPS protocols.

**Comment by arkodg** [comment] 2022-11-03 19:48
thanks for raising this issue, based on the Gateway API Spec https://gateway-api.sigs.k8s.io/guides/tls/?h=tls#clientserver-and-tls, the downstream client TLS connection should be supported

**Comment by danehans** [comment] 2022-11-03 20:35
> I'm trying to use envoy gateway as an API gateway which accepts TCP connection from a client and does SSL termination

Although I have not tested this with Envoy Gateway, it should be supported by setting the listener [protocol type](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.ProtocolType) to `TLS` and supplying an appropriate [TLS config](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.GatewayTLSConfig).

> and then proxies the request down to a service in the cluster which also accepts TCP connection with SSL using a self signed cert

The doc referenced in https://github.com/envoyproxy/gateway/issues/686#issuecomment-1302590777 details downstream TLS and TLS passthrough but does not cover upstream TLS. Upstream TLS in Gateway API is not supported until https://github.com/kubernetes-sigs/gateway-api/issues/1067 is fixed.

**Comment by danehans** [comment] 2022-12-01 22:06
Moved to backlog due to https://github.com/kubernetes-sigs/gateway-api/issues/1067.

**Comment by arkodg** [comment] 2023-02-15 04:25
dupe of https://github.com/envoyproxy/gateway/issues/837

**Closed by arkodg** 2023-02-15 04:25 UTC
Labels: enhancement, help wanted, area/translator, area/xds-server, priority/low
