### ISSUE TITLE
Terminating pods don't respond with "Connection: close" (H1) or GOAWAY(H2) on shutdown

### ISSUE THREAD

**Issue by nezdolik** [envoyproxy/gateway#4205] opened 2024-09-10 11:03 UTC
*Description*:
In graceful listener draining mode is expected that Envoy pod will respond with "Connection: close" header to clients. When deleting pod that is managed by Envoy Gateway and uses out-of-the box shutdown manager logic (which should include graceful draining), there was no indication that such header is being sent on shutdown:
```
curl  -v -H "Host: noop-http.docker.com" http://10.128.72.126:10080/ping
*   Trying 10.128.72.126:10080...
* Connected to 10.128.72.126 (10.128.72.126) port 10080
> GET /ping HTTP/1.1
> Host: noop-http.docker.com
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 200 OK
< date: Tue, 10 Sep 2024 10:32:48 GMT
< content-length: 6
< content-type: text/plain; charset=utf-8
< strict-transport-security: max-age=31536000
< x-envoy-immediate-health-check-fail: true
<
Pong!
* Connection #0 to host 10.128.72.126 left intact
```
Now testing just graceful draining admin endpoint on Envoy pod:
```
curl  -v -H "Host: noop-http.docker.com" http://10.128.82.249:10080/ping

*   Trying 10.128.82.249:10080...
* Connected to 10.128.82.249 (10.128.82.249) port 10080
> GET /ping HTTP/1.1
> Host: noop-http.docker.com
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 200 OK
< date: Tue, 10 Sep 2024 10:52:46 GMT
< content-length: 6
< content-type: text/plain; charset=utf-8
< strict-transport-security: max-age=31536000
< connection: close
<
Pong!
* Closing connection
```

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.

**Comment by nezdolik** [comment] 2024-09-10 11:48
After updating drain_type to Default fleet wide (via patch policy), terminating pod now sends "connection: close" header:
```
curl  -v -H "Host: noop-http.docker.com" http://10.128.91.214:10080/ping

*   Trying 10.128.91.214:10080...
* Connected to 10.128.91.214 (10.128.91.214) port 10080
> GET /ping HTTP/1.1
> Host: noop-http.docker.com
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 200 OK
< date: Tue, 10 Sep 2024 11:47:21 GMT
< content-length: 6
< content-type: text/plain; charset=utf-8
< strict-transport-security: max-age=31536000
< x-envoy-immediate-health-check-fail: true
< connection: close
<
Pong!
* Closing connection
```
Patch policy fragment:
```
...
    jsonPatches:
      - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
        operation:
          op: replace
          path: "/drain_type"
          value: "DEFAULT"
```

**Comment by arkodg** [comment] 2024-09-10 17:16
thanks for running these tests @nezdolik !

is this a bug in envoy ?
or 
should we swap the order of operations ? - first start graceful grain and then fail healthcheck which means the `drain_type` can be `DEFAULT`
relates to https://github.com/envoyproxy/gateway/pull/2633#discussion_r1503377540

**Comment by arkodg** [comment] 2024-09-11 18:29
hey @nezdolik I tried to reproduce this issue by deploying the QuickStart https://gateway.envoyproxy.io/docs/tasks/quickstart/

and running a curl command continuously
```
export GATEWAY_HOST=$(kubectl get gateway/eg -o jsonpath='{.status.addresses[0].value}')
while true; do curl --verbose --header "Host: www.example.com" http://$GATEWAY_HOST/get && sleep 0.5; done
```

I scaled down the deployment using
```
kubectl scale deployment/envoy-default-eg-e41e7b31 -n envoy-gateway-system --replicas=0
```

and eventually got a `connection: close` response header
```
* Connected to 127.0.0.1 (127.0.0.1) port 80
> GET /get HTTP/1.1
> Host: www.example.com
> User-Agent: curl/8.4.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-type: application/json
< x-content-type-options: nosniff
< date: Wed, 11 Sep 2024 18:23:39 GMT
< content-length: 456
< connection: close
< 
{
 "path": "/get",
 "host": "www.example.com",
 "method": "GET",
 "proto": "HTTP/1.1",
 "headers": {
  "Accept": [
   "*/*"
  ],
  "User-Agent": [
   "curl/8.4.0"
  ],
  "X-Envoy-Internal": [
   "true"
  ],
  "X-Forwarded-For": [
   "192.168.65.4"
  ],
  "X-Forwarded-Proto": [
   "http"
  ],
  "X-Request-Id": [
   "27a11036-bc75-4061-ae2f-9cda1f30d6eb"
  ]
 },
 "namespace": "default",
 "ingress": "",
 "service": "",
 "pod": "backend-69fcff487f-hx6rs"
* Closing connection
```

I dont think there is any bug and things are working as expected

**Comment by nezdolik** [comment] 2024-09-12 08:44
@arkodg interesting, I don't observe same behaviour when manually deleting the pod, e.g. in this case there was not a single "conenction: close" header until pod became unreachable (with drain type `MODIFY_ONLY`), but after switching the drain type, I immediately get "connection: close" on pod deletion (since /healthcheck/fail drains the traffic in this mode).

**Comment by arkodg** [comment] 2024-09-12 22:20
thanks for hopping on a call to debug the issue @nezdolik 

it looks like a a response with a `connection: close` is not always seen.

This is most likely due to the logic around [gradual drain strategy logic](https://github.com/envoyproxy/envoy/blob/9c16974a50a9fdc247653eea03a49da9367fa1d5/source/server/drain_manager_impl.cc#L64) which is deciding whether to drainClose or not based on a probabilistic calculation of time elapsed b/w 0 and drainTimeout (defaults to 600s), but the default minDrainTimeout is 5s, so there's a high chance we won't see any `connection: close` b/w 0-5s.
moving to `immediate` draining might be the solution here

**Closed** 2024-09-13 00:33 UTC
Labels: triage
