### ISSUE TITLE
Support Lua、Golang HTTP filters

### ISSUE THREAD

**Issue by lizj3624** [envoyproxy/gateway#2204] opened 2023-11-18 03:09 UTC
Support Lua、Golang HTTP filters，extend Envoy's capabilities, such as supporting WAF plugins and zero-trust gateway plugins

**Comment by arkodg** [comment] 2023-11-18 03:12
Closing as a duplicate of https://github.com/envoyproxy/gateway/issues/2025, @lizj3624 please add any comments missed in the other issue

**Closed by arkodg** 2023-11-18 03:12 UTC
Labels: enhancement
