### ISSUE TITLE
xds cluster OPENSSL_internal:CERTIFICATE_VERIFY_FAILED error

### ISSUE THREAD

**Issue by qicz** [envoyproxy/gateway#1889] opened 2023-09-14 12:44 UTC
*Description*:

xds TLS error

*Environment*:
> 0.5.0 

*Logs*:

```bash
[2023-09-14 12:30:34.318][1][debug][router] [source/common/router/router.cc:477] [C0][S5589304719498948233] cluster 'xds_cluster' match for URL '/envoy.service.discovery.v3.AggregatedDiscoveryService/DeltaAggregatedResources'
[2023-09-14 12:30:34.318][1][debug][router] [source/common/router/router.cc:686] [C0][S5589304719498948233] router decoding headers:
':method', 'POST'
':path', '/envoy.service.discovery.v3.AggregatedDiscoveryService/DeltaAggregatedResources'
':authority', 'xds_cluster'
':scheme', 'http'
'te', 'trailers'
'content-type', 'application/grpc'

[2023-09-14 12:30:34.319][1][debug][pool] [source/common/http/conn_pool_base.cc:76] queueing stream due to no available connections (ready=0 busy=0 connecting=0)
[2023-09-14 12:30:34.319][1][debug][pool] [source/common/conn_pool/conn_pool_base.cc:291] trying to create new connection
[2023-09-14 12:30:34.319][1][debug][connection] [./source/common/network/connection_impl.h:97] [C0] current connecting state: true
[2023-09-14 12:30:34.320][1][debug][connection] [source/common/network/connection_impl.cc:960] [C0] connection in progress
[2023-09-14 12:30:34.320][1][debug][connection] [source/common/network/connection_impl.cc:688] [C0] connected
[2023-09-14 12:30:34.424][1][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:360] [C0] Async cert validation completed
[2023-09-14 12:30:34.424][1][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:232] [C0] remote address:21.101.157.62:18000,TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
[2023-09-14 12:30:34.437][1][debug][client] [source/common/http/codec_client.cc:106] [C0] disconnect. resetting 0 pending requests
[2023-09-14 12:30:34.437][1][debug][pool] [source/common/conn_pool/conn_pool_base.cc:484] [C0] client disconnected, failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
[2023-09-14 12:30:34.437][1][debug][router] [source/common/router/router.cc:1276] [C0][S5589304719498948233] upstream reset: reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_intern
al:CERTIFICATE_VERIFY_FAILED
[2023-09-14 12:30:34.437][1][debug][http] [source/common/http/async_client_impl.cc:122] async http request response headers (end_stream=true):
':status', '200'
'content-type', 'application/grpc'
'grpc-status', '14'
'grpc-message', 'upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED'

[2023-09-14 12:30:34.437][1][debug][config] [./source/common/config/grpc_stream.h:196] DeltaAggregatedResources gRPC config stream to xds_cluster closed: 14, upstream connect error or disconnect/reset before headers. reset reason: co
nnection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
[2023-09-14 12:30:34.437][1][debug][config] [source/common/config/grpc_subscription_impl.cc:115] gRPC update for type.googleapis.com/envoy.service.runtime.v3.Runtime failed
[2023-09-14 12:30:34.437][1][debug][pool] [source/common/conn_pool/conn_pool_base.cc:453] invoking idle callbacks - is_draining_for_deletion_=false
[2023-09-14 12:30:34.830][1][debug][config] [./source/common/config/grpc_stream.h:51] Establishing new gRPC bidi stream to xds_cluster for rpc DeltaAggregatedResources(stream .envoy.service.discovery.v3.DeltaDiscoveryRequest) returns
 (stream .envoy.service.discovery.v3.DeltaDiscoveryResponse);
```

**Comment by arkodg** [comment] 2023-10-14 00:51
@qicz are you still seeing this ?

**Comment by arkodg** [comment] 2023-11-10 22:24
closing since this cannot be reproduced

**Closed by arkodg** 2023-11-10 22:24 UTC
Labels: bug

**Comment by qicz** [comment] 2024-01-17 07:07
> @qicz are you still seeing this ?

sorry reply slowly. This happens occasionally @arkodg
