### ISSUE TITLE
Add Support for User-Defined Gateway Addresses

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#360] opened 2022-09-07 21:43 UTC
#352 adds support for managing gateway status addresses. However, this PR does not support user-defined [Gateway addresses](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.GatewayAddress). Therefore, EG should compare the status address of the Gateway's associated service against the user-defined address and surface the proper Gateway status condition.

**Comment by shawnh2** [comment] 2023-04-11 12:56
hi, is this issue still available? i'd like to working on it.

**Comment by Xunzhuo** [comment] 2023-04-11 13:33
Great, thanks @shawnh2

**Comment by arkodg** [comment] 2023-04-12 17:55
@shawnh2 the Gateway API allows the user to define a custom address at the Gateway level
https://github.com/kubernetes-sigs/gateway-api/blob/a78e09220feec7947eb1a08b658b45f3b4182d7f/apis/v1beta1/gateway_types.go#L142
we need to first figure out if we / Envoy Gateway can support this feature or not i.e. can we set these addresses on the K8s Service or not.

If that is possible, we will also need to read those values and update the status https://github.com/envoyproxy/gateway/blob/f81c0118ca0c487db16ee3d54ae21e94a705a348/internal/status/gateway.go#L25

**Comment by arkodg** [comment] 2023-04-13 20:46
as @tommie suggested, the user defined gateway addresses might need to be set in `service.Spec.ExternalIPs` https://kubernetes.io/docs/concepts/services-networking/service/#external-ips in the infra mgr layer and also used to update Gateway Status

**Comment by tommie** [comment] 2023-04-14 09:13
I codified a PoC in https://github.com/envoyproxy/gateway/compare/release/v0.3...tommie:envoyproxy-gateway:external-ips?expand=1

It only cares about `IPAddress` addresses, there are no tests, etc.

Based off of v0.3 because of #1307.

**Comment by shawnh2** [comment] 2023-04-14 10:06
> I codified a PoC in https://github.com/envoyproxy/gateway/compare/release/v0.3...tommie:envoyproxy-gateway:external-ips?expand=1
> 
> It only cares about `IPAddress` addresses, there are no tests, etc.
> 
> Based off of v0.3 because of #1307.

hi, looking great, mind i merge it into my branch first? and i will complete the rest.

**Comment by tommie** [comment] 2023-04-14 10:35
@shawnh2 go for it!

**Comment by LanceEa** [comment] 2023-07-10 11:31
I see this issue is still open but was referenced by PR https://github.com/envoyproxy/gateway/pull/1322
which implemented support for `Service.spec.ExternalIPs`. However, this doesn't work for all clouds, AFAIK.

I can confirm what was mentioned here: https://github.com/envoyproxy/gateway/issues/1405#issuecomment-1538727725
is true for GKE. In GKE, it leverages the `Service.spec.loadBalancerIP`  field and the GKE admission controller actually 
fails to create the service if `ExternalIPs` is filled in. https://cloud.google.com/kubernetes-engine/docs/concepts/service-load-balancer-parameters#spd-static-ip

Looking at the K8s docs, it says the `Service.spec.loadBalancerIP` was deprecated in 1.24 https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer but it doesn't say to use the `ExternalIPs` but rather use `Gateway` which is weird because all cloud vendors don't have Gateway support. When I look at the docs for the `ExternalIPs` it has a note saying that K8s does nothing with it and it is up to cluster administrator. 

So, my questions are:

1. Is this issue still open? If so what is missing?
2. Has there been any other discussions on how to handle the Cloud Vendors that currently support the `loadBalancerIP` field of a service?

On 2, I'm happy to create a new issue if it is off topic but curious to see if there was any thought put into this.

**Comment by arkodg** [comment] 2023-07-10 18:50
@LanceEa Id prefer if we close this issue and create a new one, if we believe the feature has not been implemented correctly.
Here is the current implementation
- When a user sets [Gateway.Spec.Addresses](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.GatewayAddress) , EG sets that value to the generated managed Envoy Proxy Service's [ExternalIPs](https://kubernetes.io/docs/concepts/services-networking/service/#external-ips) field which also sets (not appends)  the  value in [Gateway.Status.Addresses](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.GatewayAddress) field

**Closed by arkodg** 2023-07-10 18:50 UTC
Labels: enhancement, provider/kubernetes
