### ISSUE TITLE
Apply EnvoyGateway config on the fly

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/gateway#1824] opened 2023-08-24 14:32 UTC
*Description*:
Allow Envoy Gateway to reconcile the updated EnvoyGateway config without restarting

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by arkodg** [comment] 2023-08-24 14:46
closing as duplicate of https://github.com/envoyproxy/gateway/issues/864

**Closed by arkodg** 2023-08-24 14:46 UTC
Labels: enhancement
