### ISSUE TITLE
Add Support for TCPRoute API

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#643] opened 2022-10-21 18:17 UTC
*Description*:
Add support for TCPRoute API defined [here](https://github.com/kubernetes-sigs/gateway-api/blob/21bba43681b3db3a62d7ca9f108bf3be4c0cea71/apis/v1alpha2/tcproute_types.go#L33)

Related https://github.com/envoyproxy/gateway/issues/47

**Comment by arkodg** [comment] 2022-10-21 18:17
we should wait on https://github.com/envoyproxy/gateway/issues/413 which will refactor the provider before starting this issue

**Comment by danehans** [comment] 2022-10-21 18:59
@arkodg this seems like a dupe of https://github.com/envoyproxy/gateway/issues/47.

**Comment by arkodg** [comment] 2022-10-21 19:11
@danehans I broke up #47 into individual issues and linked it back to #47  (one for TCP and other for UDP)

**Comment by Xunzhuo** [comment] 2022-10-23 06:54
I am assigning myself, but if this is required #413, I think the finished time cannot be measured correctly. Not sure if this can be done in v0.3.0-rc1, but let us see the progress.

**Comment by youngnick** [comment] 2022-10-28 00:08
Similarly to UDPRoute(#641), I think we need some design docs around the tradeoffs we'll need to make between transparent mode and proxy mode for TCP streams. The choice is basically between:

- transparent mode: client address available, routing changes required somehow to avoid return path check failure in transit.
- proxy mode: client address will appear to be the Envoy IP.

**Comment by arkodg** [comment] 2022-10-28 15:55
@youngnick we are already using the the [tcp_proxy filter](https://github.com/envoyproxy/gateway/blob/d572c238cfde8623046de85c06b3139479f1d7aa/internal/xds/translator/listener.go#L147) for TLS Passthrough which works well, and envoy **only supports proxy mode** for TCP (docs are [here](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto#tcp-proxy-proto)) . 
Imho this should unblock the implementation for TCPRoute in the Provider and Gateway API Translator.
To highlight this design decision of only supporting proxy mode for TCP, I can update the decision [here](https://github.com/envoyproxy/gateway/blob/main/docs/design/system-design.md#design-decisions). Are there any other considerations/decisions we should make before continuing with this implementation ?

**Comment by youngnick** [comment] 2022-11-01 03:14
I think it's fine as long as we call out the limitation. I wouldn't be surprised if people end up wanting us to put in something about PROXY mode eventually, but that seems fine to me.

**Comment by Xunzhuo** [comment] 2022-11-17 10:36
I will start to work on this, other filters implementations are blocked for the release fo v0.6.0 GWAPI.

**Closed** 2023-01-06 19:05 UTC
Labels: enhancement, area/api, priority/medium
