### ISSUE TITLE
add container image build & push

### ISSUE THREAD

**Issue by skriss** [envoyproxy/gateway#75] opened 2022-05-25 15:57 UTC
We need a container image to be built containing the `envoy-gateway` binary, and for it to be pushed to a registry. This should be able to be done locally, via `Makefile` targets, and in CI (i.e. build image on PR's, build and push image on commits to `main`). 

Building and pushing release-tagged images can probably be deferred to a separate issue that deals with release tooling.

**Comment by danehans** [comment] 2022-05-25 16:28
@skriss I think this may be a dupe of https://github.com/envoyproxy/gateway/issues/14. PTAL and comment as needed.

**Comment by skriss** [comment] 2022-05-25 16:29
Sure, I read #14 as the task of setting up the repo itself as a push target, but if you want that issue to also cover the CI work, we can close this one.

**Comment by skriss** [comment] 2022-05-25 17:09
> @skriss thanks for taking a look at #14 and providing feedback. I'm OK with keeping the separate GH issues.

:+1: they'll probably be done by different people, so sounds good to me.

**Comment by danehans** [comment] 2022-05-31 16:02
@skriss @arkodg note that `envoyproxy/gateway` and `envoyproxy/gateway-dev` docker repos have been created. The `gateway-dev` repo should contain an EG binary built from the latest tip of main that passed tests.

xref: https://github.com/envoyproxy/envoy/blob/main/ci/README.md#ubuntu-envoy-image

**Comment by arkodg** [comment] 2022-06-08 17:36
> @skriss @arkodg note that `envoyproxy/gateway` and `envoyproxy/gateway-dev` docker repos have been created. The `gateway-dev` repo should contain an EG binary built from the latest tip of main that passed tests.
> 
> xref: https://github.com/envoyproxy/envoy/blob/main/ci/README.md#ubuntu-envoy-image

CI for `envoyproxy/gateway-dev` is working. Here are the images https://hub.docker.com/r/envoyproxy/gateway-dev/tags. Keeping this issue open until the CI for release images is completed

**Comment by danehans** [comment] 2022-08-02 18:02
Per https://github.com/envoyproxy/gateway/issues/75#issuecomment-1150204451, this issue is resolved.

**Closed by danehans** 2022-08-02 18:02 UTC
Labels: area/ci
