### ISSUE TITLE
make Reconcile only when related Resources changed

### ISSUE THREAD

**Issue by spwangxp** [envoyproxy/gateway#1373] opened 2023-04-28 02:04 UTC
*Description*:
>if a cr httproute changed, envoyproxy shouldn't be build and compare, just need sync the rule. it's will make logical clear and easy to maintain.

![0414db2f27d90c5ecc5966db17f4c51](https://user-images.githubusercontent.com/24298044/235036710-cb027c7b-c3fc-49d3-960e-53d5ec322f4f.png)

**Comment by spwangxp** [comment] 2023-04-28 02:04
@qicz

**Comment by qicz** [comment] 2023-04-28 03:12
> @qicz

thanks @spwangxp I will fix this

**Comment by arkodg** [comment] 2023-04-28 15:08
is this a regression ?
imo this shouldnt be happening if the `InfraIR` content is not changing
https://github.com/envoyproxy/gateway/blob/24df11edf42c7190ed0a4348fddf7698a9ae1deb/internal/infrastructure/runner/runner.go#L65 gets called (Update) only when the value within `InfraIR` has changed

**Comment by arkodg** [comment] 2023-04-28 21:44
nvm, this is a performance optimization in the `provider` layer to reduce the k8s `List` calls for `EnvoyProxy` .
https://github.com/envoyproxy/gateway/blob/29995bd22b39b80aa14e31f9a7afaa47807c250a/internal/provider/kubernetes/controller.go#L231 can be selectively called/computed only if the `Name`, `Namespace` & `ObservedGeneration` within the `EnvoyProxy` within the `resourceTree` has changed

**Comment by arkodg** [comment] 2023-04-28 21:45
relates to https://github.com/envoyproxy/gateway/issues/1365

**Comment by qicz** [comment] 2023-04-29 00:42
> is this a regression ? imo this shouldnt be happening if the `InfraIR` content is not changing
> 
> https://github.com/envoyproxy/gateway/blob/24df11edf42c7190ed0a4348fddf7698a9ae1deb/internal/infrastructure/runner/runner.go#L65
> 
> gets called (Update) only when the value within `InfraIR` has changed

It is right, but the controller did more unnecessary processing

**Comment by qicz** [comment] 2023-04-29 01:07
> nvm, this is a performance optimization in the `provider` layer to reduce the k8s `List` calls for `EnvoyProxy` .
> 
> https://github.com/envoyproxy/gateway/blob/29995bd22b39b80aa14e31f9a7afaa47807c250a/internal/provider/kubernetes/controller.go#L231
> 
> can be selectively called/computed only if the `Name`, `Namespace` & `ObservedGeneration` within the `EnvoyProxy` within the `resourceTree` has changed

IMO, we should check all Kind that the controller watched in `resourceTree`

**Comment by arkodg** [comment] 2023-04-29 02:02
thinking again, this might be a premature optimization because, the contents from `List` should be cached

**Comment by qicz** [comment] 2023-04-29 02:35
> thinking again, this might be a premature optimization because, the contents from `List` should be cached

yep, the `watchable.Map` just handle the change.  check that all Kinds are compared  `resourceTree` and the k8s stored.

the compare logic is a matter of course.  cc @spwangxp

**Comment by spwangxp** [comment] 2023-04-29 03:32
ok, got it. thx!

**Comment by qicz** [comment] 2023-05-04 08:20
close this issue now. 

if you have another issue pls raise it. thanks @spwangxp

**Closed by qicz** 2023-05-04 08:20 UTC
Labels: provider/kubernetes, refactor, performance
